### ISSUE TITLE
Create example on how to add a method for lazy searches

### ISSUE THREAD

**Issue by miketheman** [juliandunn/library-demo-cookbook#1]
Feature request.

A library function that returns the value of a search, which is not executed at compile time, only when called in a recipe.
Also, should only be called once per run, so if multiple sub-recipes need the return value, only a single search will be performed.

**Comment by juliandunn** [comment]
That sounds like a neat thing but I don't think it belongs in a general purpose "how to write a library" cookbook. Feel free to make your own demo, though!
